// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC44otABXhhdlPmiuZPO5wfgKNfSGHIR8g',
    appId: '1:338787488952:web:b302d6d77ccf2343d7d04d',
    messagingSenderId: '338787488952',
    projectId: 'chat-app-83b8f',
    authDomain: 'chat-app-83b8f.firebaseapp.com',
    storageBucket: 'chat-app-83b8f.appspot.com',
    measurementId: 'G-XC6TVGRHS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiT-dw9JdXhXFxnyYQB0c0LXWi8kkPsEU',
    appId: '1:338787488952:android:b031e779e3ed4a55d7d04d',
    messagingSenderId: '338787488952',
    projectId: 'chat-app-83b8f',
    storageBucket: 'chat-app-83b8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ3m-JWWWexnkWaKIg2e3Mad0QVsVAD2g',
    appId: '1:338787488952:ios:1a971c3968fc12c5d7d04d',
    messagingSenderId: '338787488952',
    projectId: 'chat-app-83b8f',
    storageBucket: 'chat-app-83b8f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
